---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-logistic
  labels:
    app: fe-logistic
  namespace: fe-logistic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-logistic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fe-logistic
    spec:
      imagePullSecrets:
      - name: registry
      containers:
      - name: fe-logistic
        image: git.edenfarm.id:5050/project-version3/erp-dashboard/logistic/uat:<VERSION>
        ports:
          - name: http-port
            containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: 50Mi
            cpu: 15m
          limits:
            memory: 350Mi
            cpu: 200m
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Jakarta
            type: File
      tolerations:
      - key: instance_type
        value: service
        effect: NoSchedule
        operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - devops
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fe-logistic
            topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: svc-fe-logistic
  namespace: fe-logistic
  labels:
    app: fe-logistic
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-port
  selector:
    app: fe-logistic
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-fe-logistic
  namespace: fe-logistic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fe-logistic
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fe-logistic
  namespace: fe-logistic
spec:
  dnsNames:
    - uat-fe-logistic.edenfarm.tech
  secretName: fe-logistic-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: fe-logistic
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: fe-logistic
spec:
  tls:
  - hosts:
    - uat-fe-logistic.edenfarm.tech
    secretName: fe-logistic-tls
  rules:
  - host: uat-fe-logistic.edenfarm.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-fe-logistic
            port:
              number: 80
